### ISSUE TITLE
Error 500 when running

### ISSUE THREAD

**Issue by YerkoPalma** [pouchdb/add-cors-to-couchdb#18]
I was following [this guide](https://pouchdb.com/guides/setup-couchdb.html) and in the `Set up CORS` section, I'm having troubles. I installed this package, but when I try to run I get this error

```text
Error: status 500 {"error":"error","reason":"eacces"}
```

I've tried with node v6.0.0 and v4.4.0, I get the same error. Nove v6 give this, apparently useless, stacktrace

```text
at /home/yerko/.nvm/versions/node/v6.0.0/lib/node_modules/add-cors-to-couchdb/index.js:45:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Is this an error with my couchDB set up? I know is properly installed, I can access to `http://localhost:5984/_utils/fauxton/#/` with no problem. What could be the issue?

ps: I've installed couchDB following [this guide](https://forum.cozy.io/t/how-to-install-couchdb-manually-on-debian-jessie/1230). I'm using Debian 8

**Comment by ghost** [comment]
I was receiving the same error on OpenSUSE Leap 42.3, when trying to run the following command:

`~> sudo /usr/local/bin/add-cors-to-couchdb `
`Error: status 500 {"error":"error","reason":"eacces"}`

`     at /usr/local/lib/node_modules/add-cors-to-couchdb/index.js:45:13`
`    at <anonymous> `
`    at process._tickCallback (internal/process/next_tick.js:188:7) `


I **re-installed** CouchDB and then the error got resolved
