### ISSUE TITLE
Error accessing cloudant db URL from node

### ISSUE THREAD

**Issue by rojagit** [pouchdb/add-cors-to-couchdb#23]
Hi, I get this error accessing my db URL in cloudant: (URL has been edited)

$ add-cors-to-couchdb https://XXX83e-5af3-41de-b499-dae33fb39b69-bluemix.cloudant.com/DBNAME
Error: status 400 {"error":"illegal_docid","reason":"Only reserved document ids may start with underscore."}

    at /home/cos/.npm-global/lib/node_modules/add-cors-to-couchdb/index.js:45:13
    at process._tickCallback (internal/process/next_tick.js:109:7)

Error: status 400 {"error":"illegal_docid","reason":"Only reserved document ids may start with underscore."}

I even tried with  user & Anon Full Access

The URL works fine in browser

**Comment by nawolyniec** [comment]
I got the exact same problem, any idea how to solve it?
